const ktkktAdBlock = new
    AdBlock(
'#container,\
#ft_CFdivdlST_B_1,\
#ft_CFdivdlST_B_0,\
#cs_DIV_cscpvrich6253B,\
#fdsbarBox,#mvdiv_2169648_holder\
,#ifr2169648\
,#ft_CFdivdlST_B_0\
,#adfdiv\
,.logo\
,.top980\
,#LELE_ShowDIV_UNIONtop\
,script[src="/js/tvb/bottom960.js"]\
,script[src="http://rjs.niuxgame77.com/r/f.php?uid=144&pid=4072"]\
,#footer\
,#span_mytvb\
'
    );
